name: External Registry Integration Request
description: Request support for a new external package registry (.deb, .exe, etc.)
title: "[Registry Integration]: "
labels: [enhancement, registry-integration]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an external registry integration! This form helps us evaluate and prioritize support for new package formats and registries.

  - type: input
    id: registry_name
    attributes:
      label: Registry/Package Format Name
      description: What is the name of the registry or package format you want to integrate?
      placeholder: ex. Debian APT, Chocolatey, NuGet, PyPI
    validations:
      required: true

  - type: dropdown
    id: package_format
    attributes:
      label: Package Format Type
      description: What type of packages does this registry handle?
      options:
        - Debian packages (.deb)
        - Windows executables (.exe, .msi)
        - RPM packages (.rpm)
        - Python packages (.whl, .tar.gz)
        - Node.js packages (.tgz)
        - Java packages (.jar, .war)
        - Docker images
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: registry_url
    attributes:
      label: Registry URL/Documentation
      description: Provide the official URL or documentation for this registry
      placeholder: ex. https://www.debian.org/doc/debian-policy/
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Integration Description
      description: Describe the registry and why you'd like to see it integrated with our service.
      placeholder: |
        ex. Debian APT is the package management system used by Debian and Ubuntu distributions. 
        Integrating it would allow users to easily install and manage .deb packages through our registry service.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: How would you use this integration? What problem would it solve?
      placeholder: |
        ex. Our organization uses Ubuntu servers and we need to manage internal .deb packages. 
        Having APT integration would allow us to use our existing packages with the Sky Genesis registry.
    validations:
      required: true

  - type: textarea
    id: technical_details
    attributes:
      label: Technical Requirements
      description: What are the technical requirements for this integration?
      placeholder: |
        ex. 
        - Need to support package metadata parsing
        - Dependency resolution for .deb packages
        - GPG signature verification
        - Multi-architecture support (amd64, arm64)
        - Integration with existing APT repositories
    validations:
      required: false

  - type: dropdown
    id: authentication
    attributes:
      label: Authentication Method
      description: How does this registry handle authentication?
      options:
        - No authentication required
        - API Key/Token
        - Username/Password
        - GPG/PGP keys
        - OAuth 2.0
        - Custom authentication
        - Not sure/Need to research
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this integration for your use case?
      options:
        - Critical - Blocking our adoption
        - High - Significant impact on workflow
        - Medium - Would improve efficiency
        - Low - Nice to have
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Example Packages/Repositories
      description: Provide examples of packages or repositories you want to integrate
      placeholder: |
        ex. 
        - Internal company packages: company-app_1.2.3_amd64.deb
        - Public repositories: http://archive.ubuntu.com/ubuntu/
        - Custom repositories: http://packages.company.com/internal/
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there any workarounds or alternative approaches you've considered?
      placeholder: ex. Currently manually downloading packages and uploading them through the admin interface...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing to this integration?
      options:
        - label: I can help with testing and feedback
          required: false
        - label: I can provide technical documentation
          required: false
        - label: I can contribute code implementation
          required: false
        - label: I cannot contribute at this time
          required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      options:
        - label: I have searched for existing similar integration requests
          required: true
        - label: I have checked that this registry is publicly accessible
          required: true
        - label: I have provided sufficient technical details for evaluation
          required: true